### ISSUE TITLE
Is this useful to Swift？

### ISSUE THREAD

**Issue by codwam** [johnno1962/Remote#2]

**Comment by johnno1962** [comment]
No reason it wouldn’t work with a swift based app but it is untested

**Comment by codwam** [comment]
It builds failed when created a new Swift example and Patch it.

**Comment by johnno1962** [comment]
The way it works, you'll need to add dummy(empty) main.m to your pproject

**Comment by codwam** [comment]
Yes, I add it.

typedef NS_ENUM(int, RMTouchPhase) {
    RMTouchBeganDouble = -1,
    RMTouchBegan = 0,
    RMTouchMoved,
    RMTouchStationary,
    RMTouchEnded,
    RMTouchCancelled,
    RMTouchUseScale,
};
It has error.
RemoteCapture.h:27:42: Function definition declared 'typedef'

**Comment by johnno1962** [comment]
I’ve pushed a change to fix this. Thanks for the report!

**Comment by codwam** [comment]
Thanks
