### ISSUE TITLE
Can't compile on macOS 10.12 because of QTKit

### ISSUE THREAD

**Issue by drptbl** [johnno1962/Remote#3]
Hey,

I'm getting an error while trying to build this project.

Error message:
`QTKit/QTKit.h file not found (RMMacroManager.m)`

In macOS 10.12, Apple removed most of QTKit's components (that's probably cause of my issue) and I'm not able to build this project anymore. Is there any way to fix that/workaround?

Cheers,
drptbl.

**Comment by johnno1962** [comment]
You need to build with 7.3.1 at the moment. QuickTime Kit has been deprecated :(

**Comment by johnno1962** [comment]
I’ve pused a version that build under Xcode 8. If you want to be able to record movies build using Xcode 7.X.

**Comment by drptbl** [comment]
@johnno1962 Thank you very much for a quick fix! Actually my use case is just to test stuff on iPhone remotely to make testing faster, so I don't need to record movies and I'm happy with current solution :)

**Comment by johnno1962** [comment]
Recording still works if you copy QuickTime.framework and QTKit.framework into the platform.
