### ISSUE TITLE
How are asynchronous events handled?

### ISSUE THREAD

**Issue by REN-LEI** [johnno1962/Remote#7]

**Comment by johnno1962** [comment]
How do you mean? They are all posted on the main thread.

**Comment by REN-LEI** [comment]
> How do you mean? They are all posted on the main thread.

When I have not yet obtained data from the network, the button is not available at this time, and the remote operation is invalid.

**Comment by johnno1962** [comment]
It causes a crash? All Remote does is forward events. It has know way of knowing if they are valid.
