### ISSUE TITLE
there is a error in RemoteBundle-Prefix.pch

### ISSUE THREAD

**Issue by safuter** [johnno1962/Remote#9]
the error is:
UIKit/UIKit.h' file not found
UIKit is not available when building for macOS. Consider using `#if !TARGET_OS_OSX` to conditionally import this framework, first importing TargetConditionals.h if necessary.

My Xcode version is 12.1
How can I do?

**Comment by johnno1962** [comment]
Hi, I've only seen this error if you are building the RemoteBundle target which shouldn't be built in isolation. The project is left setup to build the Remote Xcode plugin which doesn't work any more. You should be importing the project as a Swift Package in your app instead and using it with the InjectionIII application.
